// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token              *string `json:"token,omitempty"`
	Refresh            *string `json:"refresh,omitempty"`
	User               *User   `json:"user,omitempty"`
	AccessTokenExpiry  *string `json:"accessTokenExpiry,omitempty"`
	RefreshTokenExpiry *string `json:"refreshTokenExpiry,omitempty"`
}

type CreateEmployeeInput struct {
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID string `json:"departmentID"`
	Position     string `json:"position"`
}

type DeleteEmployeeResponse struct {
	DeleteEmployeeID string `json:"deleteEmployeeId"`
}

type Employee struct {
	ID           string  `json:"id"`
	UserID       string  `json:"userID"`
	FirstName    string  `json:"firstName"`
	LastName     string  `json:"lastName"`
	Password     string  `json:"password"`
	Email        string  `json:"email"`
	Dob          string  `json:"dob"`
	DepartmentID *string `json:"departmentID,omitempty"`
	Position     string  `json:"position"`
}

type UpdateEmployeeInput struct {
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID string `json:"departmentID"`
	Position     string `json:"position"`
}

type User struct {
	ID        string  `json:"id"`
	UserName  string  `json:"userName"`
	Password  string  `json:"password"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type UserRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}
